# Generated by Django 5.0.7 on 2024-07-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="books",
            old_name="tittle",
            new_name="title",
        ),
        migrations.AddField(
            model_name="books",
            name="create_at",
            field=models.DateField(auto_now_add=True, default="2024-01-01"),
            preserve_default=False,
        ),
    ]
